name: dummy-redis
recipe: wordpress
config:
  via: nginx
  php: 7.4
  webroot: wordpress
  database: mariadb
services:
  rediscache:
    type: redis
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
  appserver:
    overrides:
      volumes:
        - '.lando.wp-cli.yml:/wp-cli.yml'
        - './client-mu-plugins:/app/wordpress/wp-content/client-mu-plugins'
        - './private:/app/wordpress/wp-content/private'
        - './images:/app/wordpress/wp-content/images'
        - './languages:/app/wordpress/wp-content/languages'
        - './themes:/app/wordpress/wp-content/themes'
        - './plugins:/app/wordpress/wp-content/plugins'
        - './uploads:/app/wordpress/wp-content/uploads'
        - './vip-config:/app/wordpress/wp-content/vip-config'
        - './mu-plugins:/app/wordpress/wp-content/mu-plugins'
    build:
      - wp core download --force --skip-content --path=/app/wordpress
      - | # Remove everything from mu-plugins directory, and clone VIP's repo
        if [ -d mu-plugins ]; then
          rm -rf mu-plugins/*
          rm -rf mu-plugins/.* 2> /dev/null
        fi
        git clone https://github.com/Automattic/vip-go-mu-plugins.git --recursive mu-plugins
    run:
      - | # Remove wp-config.php if it exists
        if [ -f wordpress/wp-config.php ]; then
          rm wordpress/wp-config.php
        fi
      - sleep 2 # For some reason, we have to wait at least a second till database is up.
      - | # Create WordPress config file and add necessary constants and custom config
        wp config create --dbhost=database --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbprefix=wp_ --extra-php <<PHP
        if ( file_exists( __DIR__ . '/wp-content/vip-config/vip-config.php' ) ) {
          require_once( __DIR__ . '/wp-content/vip-config/vip-config.php' );
        }
        PHP
      - wp config set WP_ALLOW_MULTISITE true --raw
      - wp config set WP_DEBUG true --raw
      - wp config set WP_DEBUG_LOG true --raw
      - wp config set WP_DEBUG_DISPLAY false --raw
      - wp config set VIP_GO_APP_ENVIRONMENT 'develop'
      - wp config set WP_ENVIRONMENT_TYPE 'development'
      - wp config set DISALLOW_FILE_EDIT true --raw
      - wp config set DISALLOW_FILE_MODS true --raw
      - wp config set AUTOMATIC_UPDATER_DISABLED true --raw
      - wp config set WP_REDIS_HOST 'rediscache'
      - wp core install --url=https://$LANDO_APP_NAME.$LANDO_DOMAIN --title=$LANDO_APP_NAME --admin_user=rtcamp --admin_email=admin@example.com --admin_password=GoodWork
      - wp plugin install redis-cache --activate
      - cp /app/wordpress/wp-content/plugins/redis-cache/includes/object-cache.php /app/wordpress/wp-content/object-cache.php
      - wp redis enable
      - | # Import sql file if it exists
        if [ -f lando.sql ]; then
          wp db import lando.sql
        fi

